const PublicPriceUSD = 1000;
const PrivatePriceUSD = 2000;
const ProviderPriceUSD = 2500;
const CertificatePriceUSD = 500;
const OwnerRefundPriceUSD = 200;
// Mock ------------------
const rate = 1000000000000;
const decimals = 0;
const initNodes = ["0xf48fea3be10b651407ef19aa331df17a59251f41cbd949d07560de8f3636b9d4", "0xfb2b320dd4db2d98782dcf0e70619f558862e1d313050e2408ea439c20a10799"]
const reverseHashName = "0xa097f6721ce401e757d1223a763fef49b8b5f90bb18567ddb86fd205dff71d34"
const ethHashName = "0x93cdeb708b7545dc668eb9280176169d1c33cfd8ed6f04690a0bcc88a93fc4ae"
const aljomoarEthHashName = "0xb1fe26b45b845782dfed1cc603f1684b2fbd9d9cdc7e9f309f9260a624ea79ce"
const blockcertsAljomoarEthHashName = "0xe30ca74a70585a5ccb0c21f7acb47c69a54d3cdcb4176662aa7c12a9441ac2a5"
// Mock ------------------
const TotalTokenSupply = 1000;
const PropositionLifeTime = 604800;
const PropositionThreshold = 500;
const minToPropose = 50;
const Gas = 6721975;
const PublicPoolContractName = "Public Certificate Pool";
const PublicPoolContractVersion = "1.0";
const PrivatePoolContractName = "Private Certificate Pool";
const PrivatePoolContractVersion = "1.0";
const CertificateManagerContractName = "Certificate Manager";
const CertificateManagerContractVersion = "1.0";
const TreasuryContractName = "Treasury";
const TreasuryContractVersion = "1.0";
const PriceConverterContractName = "Price Converter";
const PriceConverterContractVersion = "1.0";
const PropositionSettingsContractName = "Proposition Settings";
const PropositionSettingsContractVersion = "1.0";
const ENSContractName = "ENS";
const ENSContractVersion = "1.0";
const AdminContractName = "Admin";
const AdminContractVersion = "1.0";

exports.PublicPriceUSD = PublicPriceUSD;
exports.PrivatePriceUSD = PrivatePriceUSD;
exports.ProviderPriceUSD = ProviderPriceUSD;
exports.CertificatePriceUSD = CertificatePriceUSD;
exports.OwnerRefundPriceUSD = OwnerRefundPriceUSD;
// Mock ------------------
exports.rate = rate;
exports.decimals = decimals;
exports.initNodes = initNodes;
exports.reverseHashName = reverseHashName;
exports.ethHashName = ethHashName;
exports.aljomoarEthHashName = aljomoarEthHashName;
exports.blockcertsAljomoarEthHashName = blockcertsAljomoarEthHashName;
// Mock ------------------
exports.TotalTokenSupply = TotalTokenSupply;
exports.PropositionLifeTime = PropositionLifeTime;
exports.PropositionThreshold = PropositionThreshold;
exports.minToPropose = minToPropose;
exports.Gas = Gas;
exports.PublicPoolContractName = PublicPoolContractName;
exports.PublicPoolContractVersion = PublicPoolContractVersion;
exports.PrivatePoolContractName = PrivatePoolContractName;
exports.PrivatePoolContractVersion = PrivatePoolContractVersion;
exports.CertificateManagerContractName = CertificateManagerContractName;
exports.CertificateManagerContractVersion = CertificateManagerContractVersion;
exports.TreasuryContractName = TreasuryContractName;
exports.TreasuryContractVersion = TreasuryContractVersion;
exports.PriceConverterContractName = PriceConverterContractName;
exports.PriceConverterContractVersion = PriceConverterContractVersion;
exports.PropositionSettingsContractName = PropositionSettingsContractName;
exports.PropositionSettingsContractVersion = PropositionSettingsContractVersion;
exports.ENSContractName = ENSContractName;
exports.ENSContractVersion = ENSContractVersion;
exports.AdminContractName = AdminContractName;
exports.AdminContractVersion = AdminContractVersion;
