const PublicPriceUSD = 1000;
const PrivatePriceUSD = 2000;
const ProviderPriceUSD = 2500;
const CertificatePriceUSD = 500;
const OwnerRefundPriceUSD = 200;
const rate = 1000000000000; // Mock
const decimals = 0; // Mock
const TotalTokenSupply = 1000;
const PropositionLifeTime = 604800;
const PropositionThresholdPercentage = 50;
const minPercentageToPropose = 5;
const Gas = 6721975;
const PublicPoolContractName = "Public Certificate Pool";
const PublicPoolContractVersion = "1.0";
const PrivatePoolContractName = "Private Certificate Pool";
const PrivatePoolContractVersion = "1.0";

exports.PublicPriceUSD = PublicPriceUSD;
exports.PrivatePriceUSD = PrivatePriceUSD;
exports.ProviderPriceUSD = ProviderPriceUSD;
exports.CertificatePriceUSD = CertificatePriceUSD;
exports.OwnerRefundPriceUSD = OwnerRefundPriceUSD;
exports.rate = rate; // Mock
exports.decimals = decimals; // Mock
exports.TotalTokenSupply = TotalTokenSupply;
exports.PropositionLifeTime = PropositionLifeTime;
exports.PropositionThresholdPercentage = PropositionThresholdPercentage;
exports.minPercentageToPropose = minPercentageToPropose;
exports.Gas = Gas;
exports.PublicPoolContractName = PublicPoolContractName;
exports.PublicPoolContractVersion = PublicPoolContractVersion;
exports.PrivatePoolContractName = PrivatePoolContractName;
exports.PrivatePoolContractVersion = PrivatePoolContractVersion;
