const PublicPriceUSD = 10;
const PrivatePriceUSD = 20;
const ProviderPriceUSD = 25;
const CertificatePriceUSD = 5;
const OwnerRefundPriceUSD = 2;
const factor = 1; // Mock
const decimals = 0; // Mock
const TotalTokenSupply = 1000;
const PropositionLifeTime = 604800;
const PropositionThresholdPercentage = 50;
const minPercentageToPropose = 5;
const Gas = 6721975;

exports.PublicPriceUSD = PublicPriceUSD;
exports.PrivatePriceUSD = PrivatePriceUSD;
exports.ProviderPriceUSD = ProviderPriceUSD;
exports.CertificatePriceUSD = CertificatePriceUSD;
exports.OwnerRefundPriceUSD = OwnerRefundPriceUSD;
exports.factor = factor; // Mock
exports.decimals = decimals; // Mock
exports.TotalTokenSupply = TotalTokenSupply;
exports.PropositionLifeTime = PropositionLifeTime;
exports.PropositionThresholdPercentage = PropositionThresholdPercentage;
exports.minPercentageToPropose = minPercentageToPropose;
exports.Gas = Gas;
